source "https://rubygems.org"

gem "jekyll", "~> 4.2.0"
gem "minima", "~> 2.5"
gem "jekyll-feed", "~> 0.12"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-seo-tag", "~> 2.6"
gem "jekyll-paginate", "~> 1.1"
gem "jekyll-sass-converter", "~> 2.1.0"
